# Generated by Django 3.2.7 on 2021-09-05 11:03

import apps.resume.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSendingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_interval', models.CharField(choices=[(8, 'каждые 8 часов'), (12, 'каждые 12 часов'), (24, 'каждые 24 часа')], default=24, max_length=2, verbose_name='интервал рассылки')),
                ('stop_date_sending', models.DateField(default=apps.resume.models.default_stop_date, help_text='не больше 30 дней', verbose_name='дата остановки рассылки резюме')),
            ],
            options={
                'verbose_name': 'настройки рассылки',
                'verbose_name_plural': 'настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=255, verbose_name='название вакансии')),
                ('company', models.CharField(max_length=255, verbose_name='название компании')),
                ('link', models.CharField(max_length=255, verbose_name='ссылка на страницу вакансии')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=255, verbose_name='название резюме')),
                ('cover_letter', models.CharField(blank=True, max_length=10000, null=True, verbose_name='сопроводительное письмо')),
                ('filtered_link', models.CharField(max_length=255, verbose_name='ссылка на hh.ru с примененными фильтрами поиска вакансий')),
                ('resume_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_settings', to='resume.resumesendingsettings', verbose_name='настройки рассылки резюме')),
            ],
            options={
                'verbose_name': 'резюме',
            },
        ),
    ]
